-- +goose Up
CREATE TABLE IF NOT EXISTS scan_cursor (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    last_safe_block_processed BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DROP TABLE IF EXISTS scan_cursor;
